apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
          - "-nginx.scrape-uri=http://nginx-thrift.default.svc.cluster.local:8080/nginx_status"
        ports:
          - name: metrics
            containerPort: 9113
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  selector:
    app: nginx-prometheus-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
